project:
  type: website
  output-dir: _build

website:
  title: "BEAR"
  description: "An integrated building entity dataset"
  repo-url: https://github.com/owp-spatial/bear
  repo-actions: [issue]
  repo-subdir: docs
  page-navigation: true
  navbar:
    background: "#003087"
    foreground: "#ffffff"
    search: true
    left:
      - text: "Reference"
        href: reference/
    tools:
      - icon: github
        href: https://github.com/owp-spatial/bear
        aria-label: BEAR GitHub Repository
        target: _blank

  sidebar:
    - id: reference
      contents: "_sidebar.yml"

quartodoc:
  style: pkgdown
  title: "Built Environment Asset Registry"
  package: bear
  sidebar: _sidebar.yml
  renderer:
    style: markdown
    show_signature_annotations: true

  sections:
    - title: Providers
      desc: ""
      contents:
        - package: bear.typing
          name: Provider
        - package: bear.providers.registry
          name: ProviderRegistry
        - package: bear.providers.provider_microsoft
          name: MicrosoftProvider
        - package: bear.providers.provider_nad
          name: NADProvider
        - package: bear.providers.provider_openaddresses
          name: OpenAddressesProvider
        - package: bear.providers.provider_openstreetmap
          name: OpenStreetMapProvider
        - package: bear.providers.provider_usa_structures
          name: USAStructuresProvider

metadata-files:
  - _sidebar.yml

parser: numpy

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
