name: CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "pyproject.toml"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install libpostal
        run: >
          git clone https://github.com/openvenues/libpostal
          cd libpostal
          ./bootstrap.sh

          mkdir -p .private/libpostal
          ./configure --datadir=.private/libpostal
          sudo make -j8
          sudo make install

      - name: Install the project
        run: uv sync --dev

      # TODO(justin): test coverage
      # TODO(justin): ruff linting
      - name: Run tests
        run: uv run pytest
